id: P3B564583
initial_creation_type: ocr
source_metadata:
  volumes:
    5da8778343054378948796d7a6996789:
      base_file: v093.txt
      image_group_id: I1PD95938
      title: གཞུང་ལུགས་ཀྱི་བྱེ་བྲག་བཀོད་པའི་འཁོར་ལོ།
      total_pages: 1484
      volume_number: 93
